name: portoli
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true
  
dependencies:
  flutter:
    sdk: flutter
  intl: "^0.16.0"
  logger: ^0.8.3
  carousel_slider: ^1.3.1
  validators: "^2.0.0" 
  string_similarity: "^1.0.1"
  flutter_slidable: "^0.5.4"
  flutter_spinkit: "^4.0.0"
  flutter_datetime_picker: "^1.2.8"
  preferences: ^5.0.2
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  google_sign_in: ^4.1.1
  cupertino_icons: ^0.1.2
  form_bloc: ^0.7.0
  flutter_form_bloc: ^0.6.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  get_it: ^3.0.0+1
  back_button_interceptor: ^4.1.1
  flutter_progress_button: ^1.0.0
  material_design_icons_flutter: ^3.4.4795
  fl_chart: ^0.5.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"